name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Docker build
      run: |
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        docker build -t codesoom-cicd .
        docker tag codesoom-cicd hannut1/codesoom-cicd:${GITHUB_SHA::7}
        docker push hannut1/codesoom-cicd:${GITHUB_SHA::7}
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ec2-52-78-23-209.ap-northeast-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
          docker pull hannut1/codesoom-cicd:${GITHUB_SHA::7}
          docker tag hannut1/codesoom-cicd:${GITHUB_SHA::7} codesoom-cicd
          docker stop server
          docker run -d --rm --name server -p 80:3000 codesoom-cicd
